split:
  test_size: 0.2
  random_state: 42

gridsearch: 
  param_grid:
    n_estimators: [50, 100, 200]
    max_depth: [null, 10, 20] 
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
  cv: 5
  scoring: neg_mean_squared_error
